<table style="width: 100%;">
    <tr>
        <th>Name</th>
        <td><?php echo $address->name; ?></td>
    </tr>
    <tr><td colspan="2">Address</td></tr>
    <tr>
        <th>Street</th>
        <td><?php echo $address->street; ?></td>
    </tr>
    <tr>
        <th>City</th>
        <td><?php echo $address->city; ?></td>
    </tr>
    <tr>
        <th>State</th>
        <td><?php echo $address->state; ?></td>
    </tr>
    <tr>
        <th>Zip</th>
        <td><?php echo $address->zip; ?></td>
    </tr>
    <tr><td colspan="2">Contact</td></tr>
    <tr>
        <th>Phone #</th>
        <td><?php echo $address->phone; ?></td>
    </tr>
    <tr>
        <th>Cell #</th>
        <td><?php echo $address->cell; ?></td>
    </tr>
    <tr>
        <th>Fax #</th>
        <td><?php echo $address->fax; ?></td>
    </tr>
    <tr>
        <th>E-Mail</th>
        <td><?php echo $address->email; ?></td>
    </tr>
</table>